apiVersion: v1
kind: Template
metadata:
  name: minimal-java-app-secrets
  annotations:
    description: >-
      Secrets config for minimal-java-app
parameters:
  - name: TARGET_NAMESPACE
    description: Target namespace for this configmap
    required: true
  - name: DEPLOYMENT_NAME
    description: The name of the deployed application
    required: true
  - name: DEV
    description: developer name
    required: true
labels:
  app: minimal-java-app
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${DEPLOYMENT_NAME}-secrets
      namespace: ${TARGET_NAMESPACE}
    stringData:
      config.properties: |
        app.version="0.0.0"
        developer.name="${DEV}"

